# docker-compose.yml -- deploys files for HIPARA demo server
#	by Tin Tam <tin@hipara.org>
#

# MySQL Database Image
db:
 image: 'mysql:latest'
 volumes:
  - ./db/storage:/var/lib/mysql
 env_file: .env

redis:
 image: 'redis:latest'
 expose:
  - "6379"

web:
 restart: always
 build: .
 env_file: .env
 volumes:
  - ./hipara:/app
  - ./requirements.txt:/app/requirements.txt
  - ./run_web.sh:/app/run_web.sh
 links:
  - db:db
  - redis:redis
 ports:
  - "8008:8000"
 command: /bin/sh -c "./run_web.sh"

grr:
 restart: always
 image: 'grrdocker/grr:latest'
 ports:
  - "0.0.0.0:8001:8000"
  - "0.0.0.0:8080:8080"
 ulimits:
  nofile:
   soft: 1048576
   hard: 1048576
 env_file: ./grr/.env
 volumes:
  - ./grr/db:/var/grr-datastore
  - ./grr/logs:/var/log
  - ./grr/docker-entrypoint.sh:/docker-entrypoint.sh