# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 12:45
from __future__ import unicode_literals
from django.db import migrations
from ..models import UserMetaData, Role
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password


def data_seeder(apps, schema_editor):
    role1 = Role.objects.create(name='Super Admin')
    Role.objects.create(name='Admin')
    Role.objects.create(name='User')
    password = make_password('changedefaultpassword')
    superadmin = User.objects.create(
        password=password,
        username='Admin',
        first_name='Admin',
        last_name='Admin',
        email='user@hipara.org'
    )
    UserMetaData.objects.create(
        user=superadmin,
        role=role1,
        created_by=superadmin,
        updated_by=superadmin
    )


def data_revert(apps, schema_editors):
    from django.db import connection
    cursor = connection.cursor()
    cursor.execute('SET FOREIGN_KEY_CHECKS=0')
    cursor.execute('TRUNCATE TABLE {0}'.format(UserMetaData._meta.db_table))
    cursor.execute('TRUNCATE TABLE {0}'.format(User._meta.db_table))
    cursor.execute('TRUNCATE TABLE {0}'.format(Role._meta.db_table))
    cursor.execute('SET FOREIGN_KEY_CHECKS=1')


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=data_seeder, reverse_code=data_revert),
    ]
