# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160704_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='job_title',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
