# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alertType',
            field=models.CharField(choices=[('ALERT_FILE', 'ALERT_FILE'), ('ALERT_CMD', 'ALERT_CMD')], default='ALERT_FILE', max_length=250),
        ),
    ]
