# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alert_alerttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alertEval',
            field=models.IntegerField(choices=[(0, None), (1, 'TRUE_POSITIVE'), (2, 'FALSE_POSITIVE')], default=0),
        ),
    ]
