# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alert_alerteval'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='host_ipaddr',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='host_uuid',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='process_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
