# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion

def forwards(apps, schema_editor):
	alert = apps.get_model("alert", "Alert")
	hosts = apps.get_model("alert", "Host")
	hosts.objects.bulk_create(
		hosts(name=alerts.get('hostName'))
		for alerts in alert.objects.all().values('hostName').distinct()
	)
	for a in alert.objects.all().order_by('created_at'):
		a.host =  hosts.objects.filter(name=a.hostName).first()
		a.save()

		host = a.host
		host.last_seen = a.created_at
		host.save()


def reverse(apps, schema_editors):
	alert = apps.get_model("alert", "Alert")

	for a in alert.objects.all():
		a.hostName =  a.host.name
		a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_auto_20160908_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=128, db_index=True)),
                ('last_seen', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('uuid', 'name')]),
        ),
        migrations.AddField(
            model_name='alert',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alert.Host'),
        ),
		migrations.RunPython(forwards, reverse)
    ]
