# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-10 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_auto_20160909_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='perform_lr',
            field=models.BooleanField(default=False),
        ),
    ]
