# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_host_perform_lr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('mac', models.CharField(max_length=17)),
                ('ipv4', models.CharField(blank=True, max_length=15, null=True)),
                ('ipv6', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='grr_um',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='hardware_sn',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('uuid', 'name', 'hardware_sn')]),
        ),
        migrations.AddField(
            model_name='interface',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='alert.Host'),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('host', 'mac')]),
        ),
    ]
