# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_auto_20160925_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lrs', to='alert.Host')),
            ],
        ),
        migrations.CreateModel(
            name='LiveResponseFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'VFSRefresh'), (1, 'MemoryCollector'), (2, 'ListProcesses'), (3, 'Netstat'), (4, 'Logs'), (5, 'Cron'), (6, 'Registry')])),
                ('flow_id', models.CharField(max_length=32)),
                ('lr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='alert.LiveResponse')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='grr_file_flow_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
