# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0010_liveresponseflow_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveresponseflow',
            name='state_messages',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
