# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0011_liveresponseflow_state_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alertType',
            field=models.CharField(choices=[('ALERT_FILE', 'ALERT_FILE'), ('ALERT_CMD', 'ALERT_CMD'), ('ALERT_RANSOMWARE', 'ALERT_RANSOMWARE')], default='ALERT_FILE', max_length=250),
        ),
    ]
